# Generated by Django 2.2.7 on 2019-12-09 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=225, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('sexe', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tradeur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tradeur.Personne')),
                ('avatar', models.ImageField(null=True, upload_to='photos/')),
            ],
            bases=('tradeur.personne',),
        ),
    ]
