# Generated by Django 2.2.7 on 2019-12-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='email',
            field=models.EmailField(max_length=225, null=True),
        ),
    ]
