# Generated by Django 2.2.7 on 2019-12-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeur', '0002_auto_20191209_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='email',
            field=models.EmailField(max_length=225, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='telephone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
