# Generated by Django 2.2.7 on 2019-12-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeur', '0003_auto_20191211_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeur',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
