# Generated by Django 2.2.7 on 2019-12-09 11:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investisseur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_investissement', models.DateField(default=datetime.date.today)),
                ('date_decompte', models.DateField(default=datetime.date.today)),
                ('duree', models.PositiveSmallIntegerField(default=1)),
                ('investisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investissements', to='investisseur.Investisseur')),
            ],
        ),
    ]
