# Generated by Django 2.2.7 on 2020-01-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investisseur', '0001_initial'),
        ('investissement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investissement',
            name='investisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='investissements', to='investisseur.Investisseur'),
        ),
    ]
