# Generated by Django 2.2.7 on 2020-01-09 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investissement', '0002_investissement_investisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investissement',
            name='investisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investissements', to='investisseur.Investisseur'),
        ),
    ]
