# Generated by Django 2.2.7 on 2020-03-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investissement', '0003_auto_20200109_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='investissement',
            name='type',
            field=models.CharField(choices=[('B', 'Bloqué'), ('M', 'Mensuel')], max_length=20, null=True),
        ),
    ]
