# Generated by Django 3.0.4 on 2020-04-18 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investissement', '0004_investissement_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investissement',
            options={'ordering': ['date_decompte']},
        ),
    ]
