# Generated by Django 3.1.2 on 2020-10-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investissement', '0005_auto_20200418_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investissement',
            name='type',
        ),
        migrations.AddField(
            model_name='investissement',
            name='pack',
            field=models.CharField(choices=[('1', 'Mensuel'), ('2', 'Bloqué')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
