# Generated by Django 3.1.2 on 2020-10-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investissement', '0006_auto_20201005_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investissement',
            name='duree',
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]
