# Generated by Django 3.1.2 on 2020-10-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investissement', '0007_auto_20201005_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='investissement',
            name='taux',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=4),
        ),
    ]
