# Generated by Django 2.2.7 on 2020-01-09 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investisseur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investisseur',
            name='parrain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fieuls', to='investisseur.Investisseur'),
            preserve_default=False,
        ),
    ]
