# Generated by Django 2.2.7 on 2020-01-09 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investisseur', '0002_investisseur_parrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investisseur',
            name='parrain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieuls', to='investisseur.Investisseur'),
        ),
    ]
