# Generated by Django 2.2.7 on 2020-01-09 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investisseur', '0003_auto_20200109_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investisseur',
            name='parrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fieuls', to='investisseur.Investisseur'),
        ),
    ]
