# Generated by Django 2.2.7 on 2020-01-12 01:32

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('investisseur', '0004_auto_20200109_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='investisseur',
            name='init_password',
            field=models.CharField(default='cc', max_length=50),
            preserve_default=False,
        ),
    ]
