# Generated by Django 3.0.4 on 2020-04-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investisseur', '0005_investisseur_init_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='investisseur',
            name='mode_payement',
            field=models.CharField(choices=[('flooz', 'Flooz'), ('tmoney', 'T-Money'), ('banque', 'Compte Bancaire')], max_length=20, null=True),
        ),
    ]
