# Generated by Django 3.1.2 on 2020-10-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investisseur', '0006_investisseur_mode_payement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investisseur',
            name='mode_payement',
            field=models.CharField(choices=[('flooz', 'Flooz'), ('tmoney', 'T-Money'), ('banque', 'Compte Bancaire')], max_length=7, null=True),
        ),
    ]
