# Generated by Django 2.2.7 on 2019-12-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type_operation',
            field=models.CharField(choices=[('Retrait', 'RETRAIT'), ('Depot', 'DEPOT')], max_length=7),
        ),
    ]
