# Generated by Django 2.2.7 on 2019-12-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='libelle',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='site_web',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
