# Generated by Django 2.2.7 on 2019-12-09 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investissement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('investissement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payement', to='investissement.Investissement')),
            ],
        ),
    ]
