# Generated by Django 2.2.7 on 2020-01-06 18:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investissement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('NP', 'Non Payé'), ('PY', 'Payé')], max_length=20)),
                ('investissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payements', to='investissement.Investissement')),
            ],
        ),
    ]
