# Generated by Django 2.2.7 on 2020-01-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='status',
            field=models.CharField(choices=[('NP', 'Non Payé'), ('VR', 'Viré'), ('PY', 'Payé')], max_length=20),
        ),
    ]
