# Generated by Django 2.2.7 on 2019-12-15 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='investissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payements', to='investissement.Investissement'),
        ),
    ]
