# Generated by Django 2.2.7 on 2019-12-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payement', '0002_auto_20191215_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='payement',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
