# Generated by Django 2.2.7 on 2020-01-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payement', '0004_auto_20200114_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='status',
            field=models.CharField(choices=[('NP', 'Non Payé'), ('VR', 'Virement Effectué'), ('RE', 'Reçu')], max_length=20, null=True),
        ),
    ]
