# Generated by Django 2.2.7 on 2020-02-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payement', '0005_auto_20200114_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payement',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='payement',
            name='status',
            field=models.CharField(choices=[('NP', 'Non Payé'), ('EC', 'En Cours'), ('VR', 'Virement Effectué'), ('RE', 'Reçu')], max_length=20, null=True),
        ),
    ]
