# Generated by Django 2.2.7 on 2020-01-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=225)),
                ('date_debut', models.DateField()),
                ('duree', models.PositiveSmallIntegerField(default=5)),
                ('balance_initialisation', models.IntegerField()),
                ('objectif', models.PositiveSmallIntegerField(default=500)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciceCompte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compte.Compte')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exercice.Exercice')),
            ],
        ),
        migrations.AddField(
            model_name='exercice',
            name='comptes',
            field=models.ManyToManyField(through='exercice.ExerciceCompte', to='compte.Compte'),
        ),
    ]
