# Generated by Django 2.2.7 on 2019-12-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('duree', models.PositiveSmallIntegerField(default=5)),
                ('balance_initialisation', models.IntegerField()),
                ('objectif', models.PositiveSmallIntegerField(default=100)),
            ],
        ),
    ]
