# Generated by Django 2.2.7 on 2020-03-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='comptes',
            field=models.ManyToManyField(null=True, through='exercice.ExerciceCompte', to='compte.Compte'),
        ),
    ]
