# Generated by Django 2.2.7 on 2019-12-11 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_auto_20191211_2035'),
        ('exercice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceCompte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compte.Compte')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exercice.Exercice')),
            ],
        ),
        migrations.AddField(
            model_name='exercice',
            name='mois',
            field=models.ManyToManyField(through='exercice.ExerciceCompte', to='compte.Compte'),
        ),
    ]
