# Generated by Django 2.2.7 on 2019-12-09 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('broker', '0001_initial'),
        ('tradeur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_compte', models.CharField(max_length=225)),
                ('montant_investi', models.PositiveSmallIntegerField()),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='broker.Broker')),
                ('tradeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comptes', to='tradeur.Tradeur')),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('duree', models.PositiveSmallIntegerField(default=5)),
                ('balance_initialisation', models.IntegerField()),
                ('objectif', models.PositiveSmallIntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciceCompte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compte.Compte')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compte.Exercice')),
            ],
        ),
        migrations.CreateModel(
            name='Mois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('balance_debut', models.DateField()),
                ('balance_courante', models.IntegerField()),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mois', to='compte.ExerciceCompte')),
            ],
        ),
        migrations.AddField(
            model_name='exercice',
            name='mois',
            field=models.ManyToManyField(through='compte.ExerciceCompte', to='compte.Compte'),
        ),
    ]
