# Generated by Django 2.2.7 on 2020-01-06 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_compte', models.CharField(max_length=225, unique=True)),
                ('montant_investi', models.PositiveSmallIntegerField()),
                ('date_creation', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Mois',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('balance_debut', models.DateField()),
                ('balance_courante', models.IntegerField()),
            ],
        ),
    ]
