# Generated by Django 2.2.7 on 2019-12-11 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comptes', to='broker.Broker'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='num_compte',
            field=models.CharField(max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='compte',
            name='tradeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comptes', to='tradeur.Tradeur'),
        ),
    ]
