# Generated by Django 2.2.7 on 2019-12-11 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0002_auto_20191211_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicecompte',
            name='compte',
        ),
        migrations.RemoveField(
            model_name='exercicecompte',
            name='exercice',
        ),
        migrations.RemoveField(
            model_name='mois',
            name='exercice',
        ),
        migrations.DeleteModel(
            name='Exercice',
        ),
        migrations.DeleteModel(
            name='ExerciceCompte',
        ),
    ]
