# Generated by Django 2.2.7 on 2019-12-11 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercice', '0002_auto_20191211_2040'),
        ('compte', '0003_auto_20191211_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='mois',
            name='exercice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mois', to='exercice.ExerciceCompte'),
            preserve_default=False,
        ),
    ]
