# Generated by Django 2.2.7 on 2019-12-11 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0004_mois_exercice'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='date_creation',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
