# Generated by Django 2.2.7 on 2019-12-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0006_auto_20191211_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='tradeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comptes', to='tradeur.Tradeur'),
        ),
    ]
